main:
  - name: Syllabus
    url: /syllabus/
    weight: 1
  - name: Schedule
    url: /schedule/
    weight: 2
  - name: Classes
    url: /weeks/
    weight: 3
  - name: Resources
    identifier: resources
    weight: 4
    
  - name: Downloads
    parent: resources
    url: /downloads/
    weight: 1
  - name: Tutorials
    parent: resources
    url: /tutorials/
    weight: 2
    
  - name: CampusWire
    url: https://campuswire.com/p/GD7AC473D
    weight: 6
  - name: Blackboard
    url: https://elearning.villanova.edu
    weight: 7
